# Advance NumPy

#### NumPy array and Pyhton Lists

#### Checking the speed of NumPy array and Python Lists

In [6]:
import time
import numpy as np

In [7]:
# checking the speed of python lists

# creating python lists
a = [i for i in range(10000000)]
b =[i for i in range(10000000,20000000)]

c =  []


start = time.time()

for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time() - start)


1.1228318214416504


In [8]:
# checking the speed of numpy array

arr1 = np.arange(10000000)
arr2 = np.arange(10000000,20000000)

c =  []


start = time.time()
c = arr1 + arr2
print(time.time() - start)

0.02052903175354004


#### Now checking memory for the python lists and numpy arrays

In [4]:
# lists

li = [i for i in range(10000000)]


# sys means system
import sys

# checking memory occuped by the system
sys.getsizeof(li)

89095160

In [5]:
# numpy array

arr = np.arange(10000000)

# checking the memory occupied by the code
sys.getsizeof(arr)


# we can optimise this more by changing the int type from 64 bit to 32 bit
# numpy array

arr = np.arange(10000000,dtype=np.int32)

# checking the memory occupied by the code
sys.getsizeof(arr)

40000112

### Advance Indexing

#### Fancy indexing

In [6]:
# creating array
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
# print 1,3,4 row from the above array

# arrayname[[index]]
a[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
# print 1,3,4,6 row
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [9]:
# print 1,3,4 column
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

#### Bollean Indexing

In [10]:
# creating array

# syntax of randint -> .randint ( start(range), end(range), how many items we want)
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[30, 97, 95, 71],
       [29, 81, 11, 77],
       [16, 30, 70, 57],
       [41,  2, 98, 97],
       [15, 12, 66, 68],
       [97, 20, 45, 58]])

In [11]:
# find all numbers greater than 50
b[b > 50]

array([97, 95, 71, 81, 77, 70, 57, 98, 97, 66, 68, 97, 58])

In [12]:
# find all the even numbers
b[b % 2 == 0]

array([30, 16, 30, 70,  2, 98, 12, 66, 68, 20, 58])

In [13]:
# find all numbers greater than 50 and are even
b[(b > 50) & (b % 2 ==0)]

array([70, 98, 66, 68, 58])

In [14]:
# find all numbers greate than 50 and are odd
b[(b>50) & (b % 2 !=0)]

array([97, 95, 71, 81, 77, 57, 97, 97])

In [15]:
# find all numbers divisible by 7
b[b % 7 == 0]

array([77, 70, 98])

In [16]:
# find all numbers not divisible by 7
b[~(b % 7 == 0)]

array([30, 97, 95, 71, 29, 81, 11, 16, 30, 57, 41,  2, 97, 15, 12, 66, 68,
       97, 20, 45, 58])

#### Broadcasting

#### It describes how NumPy treats arrayof different shapes during arithmetic operations

In [4]:
# creating arrays
a = np.arange(12).reshape(4,3)
b = np.arange(3)


print(a+b)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [19]:
# this will not work because shapes are not same
a = np.arange(12).reshape(4,3)
b = np.arange(4)


In [15]:
# another example

# this will work

a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [26]:
# another example

# this will work
a = np.array([1]) # shape (1,1)
b = np.arange(4).reshape(2,2) # shape (2,2)

print(a+b)

[[1 2]
 [3 4]]


In [ ]:
# another example

# this will not work (because 1 nhi h to badhayenge kisko )
a = np.arange(12).reshape(3,4) 
b = np.arange(12).reshape(4,3) 

print(a+b)

In [ ]:
# another example

# this will not work (because 1 nhi h to badhayenge kisko )
a = np.arange(16).reshape(4,4) 
b = np.arange(4).reshape(2,2) 

print(a+b)