# Advance NumPy

#### NumPy array and Pyhton Lists

#### Checking the speed of NumPy array and Python Lists

In [33]:
import time
import numpy as np

In [32]:
# checking the speed of python lists

# creating python lists
a = [i for i in range(10000000)]
b =[i for i in range(10000000,20000000)]

c =  []


start = time.time()

for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time() - start)


1.0588138103485107


In [11]:
# checking the speed of numpy array

arr1 = np.arange(10000000)
arr2 = np.arange(10000000,20000000)

c =  []


start = time.time()
c = arr1 + arr2
print(time.time() - start)

0.0054721832275390625


#### Now checking memory for the python lists and numpy arrays

In [14]:
# lists

li = [i for i in range(10000000)]


# sys means system
import sys

# checking memory occuped by the system
sys.getsizeof(li)

89095160

In [21]:
# numpy array

arr = np.arange(10000000)

# checking the memory occupied by the code
sys.getsizeof(arr)


# we can optimise this more by changing the int type from 64 bit to 32 bit
# numpy array

arr = np.arange(10000000,dtype=np.int32)

# checking the memory occupied by the code
sys.getsizeof(arr)

40000112

### Advance Indexing

#### Fancy indexing

In [30]:
# creating array
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
# print 1,3,4 row from the above array

# arrayname[[index]]
a[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
# print 1,3,4,6 row
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [37]:
# print 1,3,4 column
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

#### Bollean Indexing

In [40]:
# creating array

# syntax of randint -> .randint ( start(range), end(range), how many items we want)
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[51, 78, 10, 19],
       [48, 84, 54, 23],
       [17,  4, 98, 61],
       [ 5, 10, 13,  8],
       [94, 73, 10, 33],
       [70, 91, 84, 97]])

In [44]:
# find all numbers greater than 50
b[b > 50]

array([51, 78, 84, 54, 98, 61, 94, 73, 70, 91, 84, 97])

In [46]:
# find all the even numbers
b[b % 2 == 0]

array([78, 10, 48, 84, 54,  4, 98, 10,  8, 94, 10, 70, 84])

In [49]:
# find all numbers greater than 50 and are even
b[(b > 50) & (b % 2 ==0)]

array([78, 84, 54, 98, 94, 70, 84])

In [51]:
# find all numbers greate than 50 and are odd
b[(b>50) & (b % 2 !=0)]

array([51, 61, 73, 91, 97])

In [55]:
# find all numbers divisible by 7
b[b % 7 == 0]

array([84, 98, 70, 91, 84])

In [57]:
# find all numbers not divisible by 7
b[~(b % 7 == 0)]

array([51, 78, 10, 19, 48, 54, 23, 17,  4, 61,  5, 10, 13,  8, 94, 73, 10,
       33, 97])

#### Broadcasting

#### It describes how NumPy treats arrayof different shapes during arithmetic operations

In [9]:
# creating arrays
a = np.arange(12).reshape(4,3)
b = np.arange(3)


print(a+b)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
# this will not work because shapes are not same
a = np.arange(12).reshape(4,3)
b = np.arange(4)

print(a+b)

In [15]:
# another example

# this will work

a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [26]:
# another example

# this will work
a = np.array([1]) # shape (1,1)
b = np.arange(4).reshape(2,2) # shape (2,2)

print(a+b)

[[1 2]
 [3 4]]


In [ ]:
# another example

# this will not work (because 1 nhi h to badhayenge kisko )
a = np.arange(12).reshape(3,4) 
b = np.arange(12).reshape(4,3) 

print(a+b)

In [ ]:
# another example

# this will not work (because 1 nhi h to badhayenge kisko )
a = np.arange(16).reshape(4,4) 
b = np.arange(4).reshape(2,2) 

print(a+b)